channels:
- conda-forge
dependencies:
- python=3.12.2
- pip<=25.1.1
- pip:
  - mlflow==3.8.1
  - cloudpickle==3.1.2
  - numpy==2.2.6
  - pandas==2.3.1
  - psutil==7.0.0
  - pyarrow==22.0.0
  - scikit-learn==1.8.0
  - scipy==1.16.2
name: mlflow-env
