FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ src/
# We assume mlruns is mounted or copied. For prod, we'd copy it or fetch from S3.
# COPY mlruns/ mlruns/

CMD ["uvicorn", "src.service.app:app", "--host", "0.0.0.0", "--port", "8000"]
